-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 20:59:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` SMALLINT(3) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medicamento` (
  `idMedicamentos` SMALLINT(3) NOT NULL,
  `NombreMedicamento` VARCHAR(45) NULL,
  `TipoMedicamento` VARCHAR(45) NOT NULL,
  `Presentacion` VARCHAR(45) NOT NULL,
  `Proveedor_idProveedor` SMALLINT(3) NOT NULL,
  PRIMARY KEY (`idMedicamentos`, `Proveedor_idProveedor`),
  INDEX `fk_Medicamentos_Proveedor_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Medicamentos_Proveedor`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctor` (
  `idDoctor` SMALLINT(3) NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `ApellidoPat` VARCHAR(20) NOT NULL,
  `ApellidoMat` VARCHAR(20) NOT NULL,
  `Direccion` VARCHAR(30) NOT NULL,
  `Telefono` INT NOT NULL,
  PRIMARY KEY (`idDoctor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clinica` (
  `idClinica` SMALLINT(3) NOT NULL,
  `Direccion` VARCHAR(30) NOT NULL,
  `Telefono` INT NOT NULL,
  PRIMARY KEY (`idClinica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `idPaciente` SMALLINT(3) NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `ApellidoPat` VARCHAR(20) NOT NULL,
  `ApellidoMat` VARCHAR(20) NOT NULL,
  `Direccion` VARCHAR(30) NOT NULL,
  `Telefono` INT NOT NULL,
  `Clinica_idClinica` SMALLINT(3) NOT NULL,
  `Doctor_idDoctor` SMALLINT(3) NOT NULL,
  PRIMARY KEY (`idPaciente`, `Clinica_idClinica`, `Doctor_idDoctor`),
  INDEX `fk_Paciente_Clinica1_idx` (`Clinica_idClinica` ASC) VISIBLE,
  INDEX `fk_Paciente_Doctor1_idx` (`Doctor_idDoctor` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_Clinica1`
    FOREIGN KEY (`Clinica_idClinica`)
    REFERENCES `mydb`.`Clinica` (`idClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_Doctor1`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `mydb`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clinica-Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clinica-Doctor` (
  `Clinica_idClinica` SMALLINT(3) NOT NULL,
  `Doctor_idDoctor` SMALLINT(3) NOT NULL,
  PRIMARY KEY (`Clinica_idClinica`, `Doctor_idDoctor`),
  INDEX `fk_Clinica_has_Doctor_Doctor1_idx` (`Doctor_idDoctor` ASC) VISIBLE,
  INDEX `fk_Clinica_has_Doctor_Clinica1_idx` (`Clinica_idClinica` ASC) VISIBLE,
  CONSTRAINT `fk_Clinica_has_Doctor_Clinica1`
    FOREIGN KEY (`Clinica_idClinica`)
    REFERENCES `mydb`.`Clinica` (`idClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clinica_has_Doctor_Doctor1`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `mydb`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clinica-Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clinica-Proveedor` (
  `Clinica_idClinica` SMALLINT(3) NOT NULL,
  `Proveedor_idProveedor` SMALLINT(3) NOT NULL,
  PRIMARY KEY (`Clinica_idClinica`, `Proveedor_idProveedor`),
  INDEX `fk_Clinica_has_Proveedor_Proveedor1_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  INDEX `fk_Clinica_has_Proveedor_Clinica1_idx` (`Clinica_idClinica` ASC) VISIBLE,
  CONSTRAINT `fk_Clinica_has_Proveedor_Clinica1`
    FOREIGN KEY (`Clinica_idClinica`)
    REFERENCES `mydb`.`Clinica` (`idClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clinica_has_Proveedor_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
